service:
  server:
    logger:
      logs_path: /path/to/webhook-bridge-service/logs/
      error_log_file: error.log
      combined_log_file: combined.log
    port: 9000
  triggers:
    example:
      actions:
