service:
  bridge:
    id: webhook_bridge_service
    hash: wbs_hash
  server:
    logger:
      logs_path: /path/to/webhook-receiver-service/logs/
      error_log_file: error.log
      combined_log_file: combined.log
    port: 9000
  triggers:
    example:
      shell: '"./path/to/shell-script"'
